-- Reverts 20260923090000_role_owner and 20260923090100_multi_business.
--
-- Multi-business tenancy was built from a misunderstanding: the requirement is
-- ONE business operating SEVERAL WhatsApp accounts (WABAs), not several isolated
-- businesses. Several WhatsApp accounts were already supported by the
-- multi-number work (numbers carry their own wabaId and token; templates are
-- keyed by wabaId), so the tenancy layer was pure unwanted complexity.
--
-- Written as a forward migration rather than by deleting the two migrations
-- above, so the recorded history stays true to what actually ran against this
-- database. Generated by `prisma migrate diff` from the live database to the
-- restored schema, plus the one partial index Prisma cannot express.
--
-- Safe to run: at the time of writing the database held no customers,
-- conversations, messages or campaigns, and no user held the OWNER role.

-- AlterEnum
BEGIN;
CREATE TYPE "Role_new" AS ENUM ('ADMIN', 'MARKETING', 'AGENT');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING ("role"::text::"Role_new");
ALTER TYPE "Role" RENAME TO "Role_old";
ALTER TYPE "Role_new" RENAME TO "Role";
DROP TYPE "Role_old";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'AGENT';
COMMIT;

-- DropForeignKey
ALTER TABLE "AuditLog" DROP CONSTRAINT "AuditLog_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Campaign" DROP CONSTRAINT "Campaign_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Campaign" DROP CONSTRAINT "Campaign_templateId_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Campaign" DROP CONSTRAINT "Campaign_whatsappNumberId_businessId_fkey";

-- DropForeignKey
ALTER TABLE "ContactList" DROP CONSTRAINT "ContactList_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Conversation" DROP CONSTRAINT "Conversation_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Conversation" DROP CONSTRAINT "Conversation_customerId_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Conversation" DROP CONSTRAINT "Conversation_whatsappNumberId_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Customer" DROP CONSTRAINT "Customer_businessId_fkey";

-- DropForeignKey
ALTER TABLE "CustomerOptOut" DROP CONSTRAINT "CustomerOptOut_businessId_fkey";

-- DropForeignKey
ALTER TABLE "CustomerOptOut" DROP CONSTRAINT "CustomerOptOut_customerId_businessId_fkey";

-- DropForeignKey
ALTER TABLE "CustomerOptOut" DROP CONSTRAINT "CustomerOptOut_whatsappNumberId_businessId_fkey";

-- DropForeignKey
ALTER TABLE "ListMember" DROP CONSTRAINT "ListMember_businessId_fkey";

-- DropForeignKey
ALTER TABLE "ListMember" DROP CONSTRAINT "ListMember_customerId_businessId_fkey";

-- DropForeignKey
ALTER TABLE "ListMember" DROP CONSTRAINT "ListMember_listId_businessId_fkey";

-- DropForeignKey
ALTER TABLE "MediaAsset" DROP CONSTRAINT "MediaAsset_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Segment" DROP CONSTRAINT "Segment_businessId_fkey";

-- DropForeignKey
ALTER TABLE "Template" DROP CONSTRAINT "Template_businessId_fkey";

-- DropForeignKey
ALTER TABLE "UserBusiness" DROP CONSTRAINT "UserBusiness_businessId_fkey";

-- DropForeignKey
ALTER TABLE "UserBusiness" DROP CONSTRAINT "UserBusiness_userId_fkey";

-- DropForeignKey
ALTER TABLE "WhatsAppNumber" DROP CONSTRAINT "WhatsAppNumber_businessId_fkey";

-- DropIndex
DROP INDEX "AuditLog_businessId_createdAt_idx";

-- DropIndex
DROP INDEX "Campaign_businessId_idx";

-- DropIndex
DROP INDEX "ContactList_businessId_idx";

-- DropIndex
DROP INDEX "ContactList_id_businessId_key";

-- DropIndex
DROP INDEX "Conversation_id_businessId_key";

-- DropIndex
DROP INDEX "Customer_businessId_chartNumber_key";

-- DropIndex
DROP INDEX "Customer_businessId_phone_key";

-- DropIndex
DROP INDEX "Customer_id_businessId_key";

-- DropIndex
DROP INDEX "MediaAsset_businessId_mediaType_idx";

-- DropIndex
DROP INDEX "Segment_businessId_idx";

-- DropIndex
DROP INDEX "Template_businessId_idx";

-- DropIndex
DROP INDEX "Template_id_businessId_key";

-- DropIndex
DROP INDEX "WhatsAppNumber_businessId_idx";

-- DropIndex
DROP INDEX "WhatsAppNumber_id_businessId_key";

-- AlterTable
ALTER TABLE "AuditLog" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "Campaign" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "ContactList" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "Conversation" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "Customer" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "CustomerOptOut" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "ListMember" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "MediaAsset" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "Segment" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "Template" DROP COLUMN "businessId";

-- AlterTable
ALTER TABLE "WhatsAppNumber" DROP COLUMN "businessId";

-- DropTable
DROP TABLE "Business";

-- DropTable
DROP TABLE "UserBusiness";

-- CreateIndex
CREATE UNIQUE INDEX "Customer_chartNumber_key" ON "Customer"("chartNumber");

-- CreateIndex
CREATE UNIQUE INDEX "Customer_phone_key" ON "Customer"("phone");

-- CreateIndex
CREATE INDEX "MediaAsset_mediaType_idx" ON "MediaAsset"("mediaType");

-- AddForeignKey
ALTER TABLE "CustomerOptOut" ADD CONSTRAINT "CustomerOptOut_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CustomerOptOut" ADD CONSTRAINT "CustomerOptOut_whatsappNumberId_fkey" FOREIGN KEY ("whatsappNumberId") REFERENCES "WhatsAppNumber"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ListMember" ADD CONSTRAINT "ListMember_listId_fkey" FOREIGN KEY ("listId") REFERENCES "ContactList"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ListMember" ADD CONSTRAINT "ListMember_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_whatsappNumberId_fkey" FOREIGN KEY ("whatsappNumberId") REFERENCES "WhatsAppNumber"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "Template"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_whatsappNumberId_fkey" FOREIGN KEY ("whatsappNumberId") REFERENCES "WhatsAppNumber"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- Restore the single-default-number index. The per-business variant was
-- dropped automatically with the businessId column above.
CREATE UNIQUE INDEX "WhatsAppNumber_single_default" ON "WhatsAppNumber"("isDefault") WHERE "isDefault";
